Repository WildCodeSchool/2023-03-js-TLSE-P2-comparimmo, pull requests merged in 2023-05, with the labels that each got.

#25 S01 us03 array data city correction
  frontend/src/components/Navbar.jsx
  frontend/src/components/arrayDataCities/ArrayDataCities.jsx
  frontend/src/components/arrayDataCities/arrayDataCities.scss
  frontend/src/pages/Home.jsx
  frontend/src/utils.js
  package-lock.json
Labels: Reviewed

#26 S03US05 Searchbar Operational
  frontend/src/components/Searchbar/Searchbar.jsx
  frontend/src/pages/Home.jsx
  package-lock.json
Labels: Reviewed, Corrections done

#27 S04US13-short-text-introduction-add the introduction in HomePage
  frontend/src/components/shortIntroduction/ShortIntroduction.jsx
  frontend/src/components/shortIntroduction/shortIntroduction.scss
  frontend/src/pages/Home.jsx
Labels: Conflicts

#28 S04US17-fix-dev-delete duplicate array and map
  frontend/src/pages/Home.jsx
Labels: Reviewed

#31 S03 us13 about
  frontend/index.html
  frontend/public/image/antoine.jpg
  frontend/public/image/cedric.jpg
  frontend/public/image/hugo.jpg
  frontend/public/image/matthieu.jpg
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/assets/img/minilogo.jpg
  frontend/src/components/Footer/Footer.module.scss
  frontend/src/components/shortIntroduction/shortIntroduction.scss
  frontend/src/pages/About.jsx
  frontend/src/pages/About.scss
  frontend/src/pages/Home.jsx
  frontend/src/utils.js
Labels: Reviewed

#32 S03US05 searchbar with button search
  frontend/src/components/Searchbar/Searchbar.jsx
  frontend/src/pages/Home.jsx
Labels: Reviewed

#33 S04 us14 display cities
  frontend/src/App.css
  frontend/src/components/Map/Map.jsx
  frontend/src/components/Searchbar/Searchbar.jsx
  frontend/src/components/arrayCitiesInput/ArrayCitiesInput.jsx
  frontend/src/components/arrayCitiesInput/arrayCitiesInput.scss
  frontend/src/components/arrayDataCities/ArrayDataCities.jsx
  frontend/src/components/carousel/Carousel.jsx
  frontend/src/pages/Home.jsx
  frontend/src/utils.js
Labels: Reviewed

#36 Dev
  frontend/index.html
  frontend/public/image/antoine.jpg
  frontend/public/image/cedric.jpg
  frontend/public/image/hugo.jpg
  frontend/public/image/matthieu.jpg
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/assets/img/minilogo.jpg
  frontend/src/assets/styles/_utils.scss
  frontend/src/assets/styles/_variables.scss
  frontend/src/components/FilterButton/filterButton.scss
  frontend/src/components/Footer/Footer.module.scss
  frontend/src/components/Map/Map.jsx
  frontend/src/components/Map/Map.module.scss
  frontend/src/components/Navbar.jsx
  frontend/src/components/Navbar.scss
  frontend/src/components/Searchbar/Searchbar.jsx
  frontend/src/components/Searchbar/searchBar.scss
  frontend/src/components/arrayCitiesInput/ArrayCitiesInput.jsx
  frontend/src/components/arrayCitiesInput/arrayCitiesInput.scss
  frontend/src/components/arrayDataCities/ArrayDataCities.jsx
  frontend/src/components/arrayDataCities/arrayDataCities.scss
  frontend/src/components/carousel/Carousel.jsx
  frontend/src/components/carousel/carousel.scss
  frontend/src/components/shortIntroduction/ShortIntroduction.jsx
  frontend/src/components/shortIntroduction/shortIntroduction.scss
  frontend/src/components/toggleButton/ToggleButton.jsx
  frontend/src/components/toggleButton/toggleButton.scss
  frontend/src/pages/About.jsx
  frontend/src/pages/About.scss
  frontend/src/pages/Home.jsx
  frontend/src/pages/Home.scss
  frontend/src/utils.js
  package-lock.json
Labels: Reviewed
